name: Terraform

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform Action to Perform'
        type: choice
        options:
          - Terraform_apply
          - Terraform_destroy

jobs:
  terraform_apply:
    name: "Terraform Apply"
    if: ${{ github.event.inputs.action == 'Terraform_apply' }}
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_bucketName: "my-unique-bucket-nameerere23r3r44"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5  # Specify the Terraform version you want to use
      

      - name: Terraform Init
        run: terraform init
        
        working-directory: terraform/

      - name: Terraform Plan
        run: terraform plan
        
        working-directory: terraform/

      - name: Terraform Apply
        run: terraform apply -auto-approve
        
        working-directory: terraform/

  terraform_destroy:
    name: "Terraform Destroy"
    if: ${{ github.event.inputs.action == 'Terraform_destroy' }}
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_bucketName: "my-unique-bucket-nameerere23r3r44"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5  # Specify the Terraform version you want to use

      - name: Terraform Init
        run: terraform init
       
        working-directory: terraform/

      - name: Show Destroy Plan
        run: terraform plan -destroy
        continue-on-error: true
        
        working-directory: terraform/

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: terraform/

          
